### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by b2410** [kurobeats/twister_script#2]
Hello,

i have with your script install twister. I can see the html-site but i have no connection.
What can i do?

**Comment by kurobeats** [comment]
Hello,
Can you please confirm if the twisterd process is running?

**Comment by b2410** [comment]
yes i can this confirm. After starting twisterd I can see the side in the browser.
Client Version: 00.09.38.00

I can change the settings. However, it finds no connection.

**Comment by b2410** [comment]
I could solve the problem.
The file twister.conf it was empty.
